# Generated by Django 6.1.1 on 2026-10-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='promo_item',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
