"""
Django settings for ratrace_project project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a)#$kom_tbg%-ggmps(u-t0e(cbh+0h&di2%7kmmt^!&gk(zi1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "daphne",  
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "channels",
    "race",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ratrace_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/"templates"],
        'APP_DIRS': True,
        'OPTIONS': {
                    'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'race.context.role',
            ],
        },
    },
]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"




ASGI_APPLICATION = "ratrace_project.asgi.application"
CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}} 


LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"



# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# ---------- Production settings (only active on Render) ----------
import os
import dj_database_url

STATIC_ROOT = BASE_DIR / "staticfiles"

if "RENDER" in os.environ:
    DEBUG = False
    SECRET_KEY = os.environ["SECRET_KEY"]
    HOST = os.environ["RENDER_EXTERNAL_HOSTNAME"]
    ALLOWED_HOSTS = [HOST]
    CSRF_TRUSTED_ORIGINS = ["https://" + HOST]
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    DATABASES["default"] = dj_database_url.config(conn_max_age=600)

    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [os.environ["REDIS_URL"]]},
        }
    }

    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
    }

    # Supabase Storage for uploaded photos
    if os.environ.get("SUPABASE_BUCKET"):
        _ref = os.environ["SUPABASE_PROJECT_REF"]
        _bucket = os.environ["SUPABASE_BUCKET"]
        STORAGES["default"] = {"BACKEND": "storages.backends.s3.S3Storage"}
        AWS_ACCESS_KEY_ID = os.environ["SUPABASE_ACCESS_KEY"]
        AWS_SECRET_ACCESS_KEY = os.environ["SUPABASE_SECRET_KEY"]
        AWS_STORAGE_BUCKET_NAME = _bucket
        AWS_S3_ENDPOINT_URL = f"https://{_ref}.storage.supabase.co/storage/v1/s3"
        AWS_S3_REGION_NAME = os.environ["SUPABASE_REGION"]
        AWS_S3_ADDRESSING_STYLE = "path"
        AWS_S3_CUSTOM_DOMAIN = f"{_ref}.supabase.co/storage/v1/object/public/{_bucket}"
        AWS_QUERYSTRING_AUTH = False
        AWS_S3_FILE_OVERWRITE = False
        AWS_DEFAULT_ACL = None